services:
  - type: web
    name: tbcc-strapi
    env: node
    plan: free
    region: singapore
    repo: https://github.com/hughlilly/tbcc-db
    branch: main
    autoDeploy: false
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true

  - type: web
    name: tbcc
    env: node
    plan: free
    region: singapore
    repo: https://github.com/hughlilly/tbcc
    branch: main
    autoDeploy: false
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: STRAPI_URL_BASE
        fromService:
          type: web
          name: tbcc-strapi
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: tbcc-db
    plan: free
    region: singapore
    databaseName: strapi_pg_prod
